/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceCalendarEarningsKrRouteImport } from './routes/_workspace.calendar-earnings-kr'
import { Route as WorkspaceCalendarEarningsUsRouteImport } from './routes/_workspace.calendar-earnings-us'
import { Route as WorkspaceCalendarEventsRouteImport } from './routes/_workspace.calendar-events'
import { Route as WorkspaceCorporationInvestmentsRouteImport } from './routes/_workspace.corporation-investments'
import { Route as WorkspaceCorporationsRouteImport } from './routes/_workspace.corporations'
import { Route as WorkspaceKrMarketDataRouteImport } from './routes/_workspace.kr-market-data'
import { Route as WorkspaceListedStocksRouteImport } from './routes/_workspace.listed-stocks'
import { Route as WorkspaceThemesRouteImport } from './routes/_workspace.themes'
import { Route as WorkspaceUsStocksRouteImport } from './routes/_workspace.us-stocks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCalendarEarningsKrRoute =
  WorkspaceCalendarEarningsKrRouteImport.update({
    id: '/calendar-earnings-kr',
    path: '/calendar-earnings-kr',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCalendarEarningsUsRoute =
  WorkspaceCalendarEarningsUsRouteImport.update({
    id: '/calendar-earnings-us',
    path: '/calendar-earnings-us',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCalendarEventsRoute = WorkspaceCalendarEventsRouteImport.update({
  id: '/calendar-events',
  path: '/calendar-events',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCorporationInvestmentsRoute =
  WorkspaceCorporationInvestmentsRouteImport.update({
    id: '/corporation-investments',
    path: '/corporation-investments',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCorporationsRoute = WorkspaceCorporationsRouteImport.update({
  id: '/corporations',
  path: '/corporations',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceKrMarketDataRoute = WorkspaceKrMarketDataRouteImport.update({
  id: '/kr-market-data',
  path: '/kr-market-data',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceListedStocksRoute = WorkspaceListedStocksRouteImport.update({
  id: '/listed-stocks',
  path: '/listed-stocks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceThemesRoute = WorkspaceThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceUsStocksRoute = WorkspaceUsStocksRouteImport.update({
  id: '/us-stocks',
  path: '/us-stocks',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar-earnings-kr': typeof WorkspaceCalendarEarningsKrRoute
  '/calendar-earnings-us': typeof WorkspaceCalendarEarningsUsRoute
  '/calendar-events': typeof WorkspaceCalendarEventsRoute
  '/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/corporations': typeof WorkspaceCorporationsRoute
  '/kr-market-data': typeof WorkspaceKrMarketDataRoute
  '/listed-stocks': typeof WorkspaceListedStocksRoute
  '/themes': typeof WorkspaceThemesRoute
  '/us-stocks': typeof WorkspaceUsStocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar-earnings-kr': typeof WorkspaceCalendarEarningsKrRoute
  '/calendar-earnings-us': typeof WorkspaceCalendarEarningsUsRoute
  '/calendar-events': typeof WorkspaceCalendarEventsRoute
  '/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/corporations': typeof WorkspaceCorporationsRoute
  '/kr-market-data': typeof WorkspaceKrMarketDataRoute
  '/listed-stocks': typeof WorkspaceListedStocksRoute
  '/themes': typeof WorkspaceThemesRoute
  '/us-stocks': typeof WorkspaceUsStocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/calendar-earnings-kr': typeof WorkspaceCalendarEarningsKrRoute
  '/_workspace/calendar-earnings-us': typeof WorkspaceCalendarEarningsUsRoute
  '/_workspace/calendar-events': typeof WorkspaceCalendarEventsRoute
  '/_workspace/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/_workspace/corporations': typeof WorkspaceCorporationsRoute
  '/_workspace/kr-market-data': typeof WorkspaceKrMarketDataRoute
  '/_workspace/listed-stocks': typeof WorkspaceListedStocksRoute
  '/_workspace/themes': typeof WorkspaceThemesRoute
  '/_workspace/us-stocks': typeof WorkspaceUsStocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar-earnings-kr'
    | '/calendar-earnings-us'
    | '/calendar-events'
    | '/corporation-investments'
    | '/corporations'
    | '/kr-market-data'
    | '/listed-stocks'
    | '/themes'
    | '/us-stocks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar-earnings-kr'
    | '/calendar-earnings-us'
    | '/calendar-events'
    | '/corporation-investments'
    | '/corporations'
    | '/kr-market-data'
    | '/listed-stocks'
    | '/themes'
    | '/us-stocks'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/_workspace/calendar-earnings-kr'
    | '/_workspace/calendar-earnings-us'
    | '/_workspace/calendar-events'
    | '/_workspace/corporation-investments'
    | '/_workspace/corporations'
    | '/_workspace/kr-market-data'
    | '/_workspace/listed-stocks'
    | '/_workspace/themes'
    | '/_workspace/us-stocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/calendar-earnings-kr': {
      id: '/_workspace/calendar-earnings-kr'
      path: '/calendar-earnings-kr'
      fullPath: '/calendar-earnings-kr'
      preLoaderRoute: typeof WorkspaceCalendarEarningsKrRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/calendar-earnings-us': {
      id: '/_workspace/calendar-earnings-us'
      path: '/calendar-earnings-us'
      fullPath: '/calendar-earnings-us'
      preLoaderRoute: typeof WorkspaceCalendarEarningsUsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/calendar-events': {
      id: '/_workspace/calendar-events'
      path: '/calendar-events'
      fullPath: '/calendar-events'
      preLoaderRoute: typeof WorkspaceCalendarEventsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/corporation-investments': {
      id: '/_workspace/corporation-investments'
      path: '/corporation-investments'
      fullPath: '/corporation-investments'
      preLoaderRoute: typeof WorkspaceCorporationInvestmentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/corporations': {
      id: '/_workspace/corporations'
      path: '/corporations'
      fullPath: '/corporations'
      preLoaderRoute: typeof WorkspaceCorporationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/kr-market-data': {
      id: '/_workspace/kr-market-data'
      path: '/kr-market-data'
      fullPath: '/kr-market-data'
      preLoaderRoute: typeof WorkspaceKrMarketDataRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/listed-stocks': {
      id: '/_workspace/listed-stocks'
      path: '/listed-stocks'
      fullPath: '/listed-stocks'
      preLoaderRoute: typeof WorkspaceListedStocksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/themes': {
      id: '/_workspace/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof WorkspaceThemesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/us-stocks': {
      id: '/_workspace/us-stocks'
      path: '/us-stocks'
      fullPath: '/us-stocks'
      preLoaderRoute: typeof WorkspaceUsStocksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceCalendarEarningsKrRoute: typeof WorkspaceCalendarEarningsKrRoute
  WorkspaceCalendarEarningsUsRoute: typeof WorkspaceCalendarEarningsUsRoute
  WorkspaceCalendarEventsRoute: typeof WorkspaceCalendarEventsRoute
  WorkspaceCorporationInvestmentsRoute: typeof WorkspaceCorporationInvestmentsRoute
  WorkspaceCorporationsRoute: typeof WorkspaceCorporationsRoute
  WorkspaceKrMarketDataRoute: typeof WorkspaceKrMarketDataRoute
  WorkspaceListedStocksRoute: typeof WorkspaceListedStocksRoute
  WorkspaceThemesRoute: typeof WorkspaceThemesRoute
  WorkspaceUsStocksRoute: typeof WorkspaceUsStocksRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceCalendarEarningsKrRoute: WorkspaceCalendarEarningsKrRoute,
  WorkspaceCalendarEarningsUsRoute: WorkspaceCalendarEarningsUsRoute,
  WorkspaceCalendarEventsRoute: WorkspaceCalendarEventsRoute,
  WorkspaceCorporationInvestmentsRoute: WorkspaceCorporationInvestmentsRoute,
  WorkspaceCorporationsRoute: WorkspaceCorporationsRoute,
  WorkspaceKrMarketDataRoute: WorkspaceKrMarketDataRoute,
  WorkspaceListedStocksRoute: WorkspaceListedStocksRoute,
  WorkspaceThemesRoute: WorkspaceThemesRoute,
  WorkspaceUsStocksRoute: WorkspaceUsStocksRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
