/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceCorporationInvestmentsRouteImport } from './routes/_workspace.corporation-investments'
import { Route as WorkspaceCorporationsRouteImport } from './routes/_workspace.corporations'
import { Route as WorkspaceListedStocksRouteImport } from './routes/_workspace.listed-stocks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCorporationInvestmentsRoute =
  WorkspaceCorporationInvestmentsRouteImport.update({
    id: '/corporation-investments',
    path: '/corporation-investments',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCorporationsRoute = WorkspaceCorporationsRouteImport.update({
  id: '/corporations',
  path: '/corporations',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceListedStocksRoute = WorkspaceListedStocksRouteImport.update({
  id: '/listed-stocks',
  path: '/listed-stocks',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/corporations': typeof WorkspaceCorporationsRoute
  '/listed-stocks': typeof WorkspaceListedStocksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/corporations': typeof WorkspaceCorporationsRoute
  '/listed-stocks': typeof WorkspaceListedStocksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/_workspace/corporations': typeof WorkspaceCorporationsRoute
  '/_workspace/listed-stocks': typeof WorkspaceListedStocksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/corporation-investments' | '/corporations' | '/listed-stocks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/corporation-investments' | '/corporations' | '/listed-stocks'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/_workspace/corporation-investments'
    | '/_workspace/corporations'
    | '/_workspace/listed-stocks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/corporation-investments': {
      id: '/_workspace/corporation-investments'
      path: '/corporation-investments'
      fullPath: '/corporation-investments'
      preLoaderRoute: typeof WorkspaceCorporationInvestmentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/corporations': {
      id: '/_workspace/corporations'
      path: '/corporations'
      fullPath: '/corporations'
      preLoaderRoute: typeof WorkspaceCorporationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/listed-stocks': {
      id: '/_workspace/listed-stocks'
      path: '/listed-stocks'
      fullPath: '/listed-stocks'
      preLoaderRoute: typeof WorkspaceListedStocksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceCorporationInvestmentsRoute: typeof WorkspaceCorporationInvestmentsRoute
  WorkspaceCorporationsRoute: typeof WorkspaceCorporationsRoute
  WorkspaceListedStocksRoute: typeof WorkspaceListedStocksRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceCorporationInvestmentsRoute: WorkspaceCorporationInvestmentsRoute,
  WorkspaceCorporationsRoute: WorkspaceCorporationsRoute,
  WorkspaceListedStocksRoute: WorkspaceListedStocksRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
