/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as WorkspaceCalendarEarningsRouteImport } from './routes/_workspace.calendar-earnings'
import { Route as WorkspaceCalendarEarningsKrxRouteImport } from './routes/_workspace.calendar-earnings-krx'
import { Route as WorkspaceCalendarEventsRouteImport } from './routes/_workspace.calendar-events'
import { Route as WorkspaceCorporationInvestmentsRouteImport } from './routes/_workspace.corporation-investments'
import { Route as WorkspaceCorporationsRouteImport } from './routes/_workspace.corporations'
import { Route as WorkspaceListedStocksRouteImport } from './routes/_workspace.listed-stocks'
import { Route as WorkspaceNasdaqsRouteImport } from './routes/_workspace.nasdaqs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceCalendarEarningsRoute =
  WorkspaceCalendarEarningsRouteImport.update({
    id: '/calendar-earnings',
    path: '/calendar-earnings',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCalendarEarningsKrxRoute =
  WorkspaceCalendarEarningsKrxRouteImport.update({
    id: '/calendar-earnings-krx',
    path: '/calendar-earnings-krx',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCalendarEventsRoute = WorkspaceCalendarEventsRouteImport.update({
  id: '/calendar-events',
  path: '/calendar-events',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCorporationInvestmentsRoute =
  WorkspaceCorporationInvestmentsRouteImport.update({
    id: '/corporation-investments',
    path: '/corporation-investments',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceCorporationsRoute = WorkspaceCorporationsRouteImport.update({
  id: '/corporations',
  path: '/corporations',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceListedStocksRoute = WorkspaceListedStocksRouteImport.update({
  id: '/listed-stocks',
  path: '/listed-stocks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceNasdaqsRoute = WorkspaceNasdaqsRouteImport.update({
  id: '/nasdaqs',
  path: '/nasdaqs',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar-earnings': typeof WorkspaceCalendarEarningsRoute
  '/calendar-earnings-krx': typeof WorkspaceCalendarEarningsKrxRoute
  '/calendar-events': typeof WorkspaceCalendarEventsRoute
  '/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/corporations': typeof WorkspaceCorporationsRoute
  '/listed-stocks': typeof WorkspaceListedStocksRoute
  '/nasdaqs': typeof WorkspaceNasdaqsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar-earnings': typeof WorkspaceCalendarEarningsRoute
  '/calendar-earnings-krx': typeof WorkspaceCalendarEarningsKrxRoute
  '/calendar-events': typeof WorkspaceCalendarEventsRoute
  '/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/corporations': typeof WorkspaceCorporationsRoute
  '/listed-stocks': typeof WorkspaceListedStocksRoute
  '/nasdaqs': typeof WorkspaceNasdaqsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_workspace/calendar-earnings': typeof WorkspaceCalendarEarningsRoute
  '/_workspace/calendar-earnings-krx': typeof WorkspaceCalendarEarningsKrxRoute
  '/_workspace/calendar-events': typeof WorkspaceCalendarEventsRoute
  '/_workspace/corporation-investments': typeof WorkspaceCorporationInvestmentsRoute
  '/_workspace/corporations': typeof WorkspaceCorporationsRoute
  '/_workspace/listed-stocks': typeof WorkspaceListedStocksRoute
  '/_workspace/nasdaqs': typeof WorkspaceNasdaqsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar-earnings'
    | '/calendar-earnings-krx'
    | '/calendar-events'
    | '/corporation-investments'
    | '/corporations'
    | '/listed-stocks'
    | '/nasdaqs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar-earnings'
    | '/calendar-earnings-krx'
    | '/calendar-events'
    | '/corporation-investments'
    | '/corporations'
    | '/listed-stocks'
    | '/nasdaqs'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/_workspace/calendar-earnings'
    | '/_workspace/calendar-earnings-krx'
    | '/_workspace/calendar-events'
    | '/_workspace/corporation-investments'
    | '/_workspace/corporations'
    | '/_workspace/listed-stocks'
    | '/_workspace/nasdaqs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/calendar-earnings': {
      id: '/_workspace/calendar-earnings'
      path: '/calendar-earnings'
      fullPath: '/calendar-earnings'
      preLoaderRoute: typeof WorkspaceCalendarEarningsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/calendar-earnings-krx': {
      id: '/_workspace/calendar-earnings-krx'
      path: '/calendar-earnings-krx'
      fullPath: '/calendar-earnings-krx'
      preLoaderRoute: typeof WorkspaceCalendarEarningsKrxRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/calendar-events': {
      id: '/_workspace/calendar-events'
      path: '/calendar-events'
      fullPath: '/calendar-events'
      preLoaderRoute: typeof WorkspaceCalendarEventsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/corporation-investments': {
      id: '/_workspace/corporation-investments'
      path: '/corporation-investments'
      fullPath: '/corporation-investments'
      preLoaderRoute: typeof WorkspaceCorporationInvestmentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/corporations': {
      id: '/_workspace/corporations'
      path: '/corporations'
      fullPath: '/corporations'
      preLoaderRoute: typeof WorkspaceCorporationsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/listed-stocks': {
      id: '/_workspace/listed-stocks'
      path: '/listed-stocks'
      fullPath: '/listed-stocks'
      preLoaderRoute: typeof WorkspaceListedStocksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/nasdaqs': {
      id: '/_workspace/nasdaqs'
      path: '/nasdaqs'
      fullPath: '/nasdaqs'
      preLoaderRoute: typeof WorkspaceNasdaqsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceCalendarEarningsRoute: typeof WorkspaceCalendarEarningsRoute
  WorkspaceCalendarEarningsKrxRoute: typeof WorkspaceCalendarEarningsKrxRoute
  WorkspaceCalendarEventsRoute: typeof WorkspaceCalendarEventsRoute
  WorkspaceCorporationInvestmentsRoute: typeof WorkspaceCorporationInvestmentsRoute
  WorkspaceCorporationsRoute: typeof WorkspaceCorporationsRoute
  WorkspaceListedStocksRoute: typeof WorkspaceListedStocksRoute
  WorkspaceNasdaqsRoute: typeof WorkspaceNasdaqsRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceCalendarEarningsRoute: WorkspaceCalendarEarningsRoute,
  WorkspaceCalendarEarningsKrxRoute: WorkspaceCalendarEarningsKrxRoute,
  WorkspaceCalendarEventsRoute: WorkspaceCalendarEventsRoute,
  WorkspaceCorporationInvestmentsRoute: WorkspaceCorporationInvestmentsRoute,
  WorkspaceCorporationsRoute: WorkspaceCorporationsRoute,
  WorkspaceListedStocksRoute: WorkspaceListedStocksRoute,
  WorkspaceNasdaqsRoute: WorkspaceNasdaqsRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
